import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { auth } from "~/server/auth";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Airtable Clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Landing_Page/Logo.svg" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="min-h-screen">
          <TRPCReactProvider>
          <SessionProvider session={session}>{children}</SessionProvider>
            </TRPCReactProvider>
        </div>
      </body>
      
    </html>
  );
}
