import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Top_Nav_Bar } from "./_components/top_nav_bar";

export const metadata: Metadata = {
  title: "Airtable Clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Landing_Page/Logo.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="min-h-screen">
          
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
      </body>
      
    </html>
  );
}
